apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-service-dp
  labels:
    app: trips-service
  namespace: staging-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-service
  template:
    metadata:
      labels:
        app: trips-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z trips-service-db-srv 3306; do echo waiting for db; sleep 2; done']
      containers:
        - name: trips-service-php
          image: docker.io/rvanappeldorn/trips-service:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_USER
              valueFrom:
                secretKeyRef: { name: trips-db-credentials, key: user }
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: trips-db-credentials, key: password }
            - name: DB_NAME
              value: "trips"
            - name: DB_PORT
              value: "3306"
            - name: DB_HOST
              value: trips-service-db-srv
          ports:
            - containerPort: 9000
        - name: trip-service-nginx
          image: nginx:1.27-alpine
          ports: 
            - containerPort: 80 
          volumeMounts:
            - name: webroot
              mountPath: /var/www/html:ro
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            tcpSocket: { port: 9000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
      volumes:
        - name: webroot
          emptyDir: {}
        - name: nginx
          configMap:
            name: trips-service-nginx-conf