services:
  accounts-service-db:
    image: mariadb:12.0.2
    restart: always
    environment:
      - MARIADB_DATABASE=accounts
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./accounts-service/mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
  mailhog:
   image: mailhog/mailhog
   ports:
     - "1025:1025"   
     - "8025:8025"  
  accounts-service:
    build: 
      context: accounts-service/
      dockerfile: Dockerfile
    user: "${USER_UID}:${GID}"   
    volumes:
      - ./accounts-service/migrations:/app/migrations
      - ./accounts-service/alembic.ini:/app/alembic.ini
    environment:
      - DATABASE_URL=mariadb+pymysql://dev:password@accounts-service-db:3306/accounts?charset=utf8mb4
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - SMTP_PORT=1025
      - SMTP_HOST=mailhog
      - SMTP_PASSWORD=
      - SMTP_USER=
      - FROM_MAIL=no-reply@example.com
      - BASE_URL=http://localhost:8000
    restart: always
    depends_on:
      - accounts-service-db
    ports:
      - 8000:8000
  trips-service-php:
    build:
      context: trips-service/
      dockerfile: Dockerfile
    user: "${USER_UID}:${GID}"   
    restart: always
  trips-service-nginx:
    image: nginx:1.27-alpine
    depends_on: 
      - trips-service-php
    ports:
      - 80:80
    volumes:
      - ./trips-service:/var/www/html:ro
      - ./trips-service/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro