[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v$version"

# Alleen deze scopes (services) toestaan
[tool.commitizen.customize]
scopes = ["account-service", "booking-service", "frontend"]
