apiVersion: v1
kind: Service
metadata:
  name: accounts-service-srv
  labels:
    app: accounts-service
  namespace: staging-ns
spec:
  type: ClusterIP
  selector: 
    app: accounts-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
