apiVersion: batch/v1
kind: Job
metadata:
  name: accounts-service-migrate
  namespace: staging-ns
  labels:
    app: accounts-service
    job: accounts-service-migrate
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template: 
    metadata:
      labels:
        app: accounts-service
        job: accounts-service-migrate
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z accounts-service-db-srv 3306; do echo waiting for db; sleep 2; done']
      containers:
      - name: migrate
        image: docker.io/rvanappeldorn/accounts-service-fast-api:latest
        imagePullPolicy: Never
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef: { name: accounts-db-credentials, key: user }
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef: { name: accounts-db-credentials, key: password }
          - name: DATABASE_URL
            value: mariadb+pymysql://$(DB_USER):$(DB_PASSWORD)@accounts-service-db-srv:3306/accounts?charset=utf8mb4
          - name: SMTP_PORT
            value: "1025"
          - name: SMTP_HOST
            value: mailhog-srv.dev-tools.svc.cluster.local
          - name: FROM_MAIL
            value: no-reply@example.com
          - name: BASE_URL
            value: staging.booking-app.com
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef: { name: accounts-service-secrets, key: jwt_secret_key }
        command: ["sh", "-c"]
        args:
          - |
            set -e
            echo "Running Alembic migrations..."
            alembic upgrade head
            echo "✅ Migrations complete"