apiVersion: v1
kind: Service
metadata:
  name: mailhog-srv
  namespace: dev-tools
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
      protocol: TCP
    - name: http
      port: 8025
      targetPort: http
      protocol: TCP
  type: ClusterIP