name: Conventional Commits (Commitizen)

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  cz-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Commitizen
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Determine PR range
        id: range
        run: |
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Lint commits in PR with Commitizen
        run: |
          cz check --rev-range ${{ steps.range.outputs.BASE_SHA }}..${{ steps.range.outputs.HEAD_SHA }}
